---
# tasks file for openvpn (Debian specific)
- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ openvpn_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - openvpn

