---
# tasks file for openvpn
- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - openvpn

- include_tasks: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - openvpn

- include_tasks: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - openvpn

- include_tasks: Debian.yml
  when: ansible_distribution == "Debian"
  tags:
    - openvpn

- name: Create OpenVPN defaults configuration file
  template:
    src: openvpn.default.j2
    dest: /etc/default/openvpn
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "trusty"
  tags:
    - openvpn

- name: Create OpenVPN defaults configuration file
  template:
    src: openvpn.default.j2
    dest: /etc/default/openvpn
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - openvpn

- name: Includo task per client
  include_tasks: client.yml
  when: openvpn_client
  tags:
    - openvpn

- name: Includo task per server
  include_tasks: server.yml
  when: openvpn_server
  tags:
    - openvpn

- name: Create OpenVPN static key
  template:
    src: static.key.j2
    dest: "{{ openvpn_secret_file }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart openvpn
  when: openvpn_static
  tags:
    - openvpn

- name: Ensure OpenVPN service is started and enabled on boot
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: started
    enabled: yes
  tags:
    - openvpn
