---
#TODO update with new repos https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos?__cf_chl_jschl_tk__=6afa67a532ad558f5089efc31f1bcdd8611dee1c-1609935578-0-AYQ3PL674_CxNrJOZgVZ7_fcE97rGdcITpC_RDEBdTHOjPVTOOpmxHKgXZYL5Sftcw5JEI_hJbUxexg1TArjkvtK2Oy1jga_aOpRJUGIT1zBRkdQv-UrS_R3zw6E_P47zpu47_MhaNA3CpoUaaBCdnxWqD6NXVX6uNIRWVoacZMoLZLD57Fthxy7A-aidtLhewg8H5hBVSUF0bGC4ejXnGlKGIlSPyocL_h45TDBNWpL-GCHoW0XOjbS27Xtgfr2GOOK5zLFz_6H2q6hCcHiulqeqxRa4UxkLFrWWRO8bD5-EhfMJ8JxzhqLazSGNdz3uvMqIdzeSKYXHMy5uY7FfabRM1Nmz8iyA3vPGniZz59I
# tasks file for openvpn (Ubuntu specific)

- name: Install OpenVPN GPG key
  become: yes
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present
  tags:
    - openvpn
  when: ansible_distribution_version is version('20.04', '<')

- name: Add OpenVPN repository
  become: yes
  apt_repository:
    repo: 'deb http://swupdate.openvpn.net/apt {{ ansible_distribution_release }} main'
    state: present
  tags:
    - openvpn
  when: ansible_distribution_version is version('20.04', '<')

- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ openvpn_packages }}"
    state: present
    update_cache: yes
  tags:
    - openvpn

- name: Fix Xenial systemd service unit file
  become: yes
  template:
    src: openvpn@.service.j2
    dest: /lib/systemd/system/openvpn@.service
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - openvpn
