---
# handlers file for openvpn

- name: reload systemd
  become: yes
  shell: "[ -f /bin/systemctl ] && systemctl daemon-reload || exit 0"
  tags:
    - openvpn

- name: restart openvpn
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: restarted
  tags:
    - openvpn

- name: save iptables
  shell: iptables-save > /etc/iptables/rules.v4
